### ISSUE TITLE
Can't build on Ubuntu 11.04 (Natty)

### ISSUE THREAD

**Issue by yuv** [codebutler/firesheep#112]
I do:

sudo apt-get install autoconf libtool libpcap-dev libboost-all-dev libhal-dev xulrunner-1.9.2-dev
git clone https://github.com/codebutler/firesheep.git
cd firesheep/
git submodule update --init
 ./autogen.sh 
make

and I get 

Making all in mozpopen
make[1]: Entering directory `/home/yuv/src/firesheep/mozpopen'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/home/yuv/src/firesheep/mozpopen'
Making all in backend
make[1]: Entering directory`/home/yuv/src/firesheep/backend'
mkdir -p ../xpi/platform/Linux_x86_64-gcc3
rm -f ../xpi/platform/Linux_x86_64-gcc3/firesheep-backend
g++ -g -O2 -DHAVE_STDARG_H -Wall -include src/config.h -g   -DPLATFORM_LINUX -mtune=generic -m64   -DDBUS_API_SUBJECT_TO_CHANGE -I/usr/include/hal -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include   -I deps/ -I deps/http-parser -I deps/json_spirit       -L/usr/lib  -lpcap   -L/lib -lhal -ldbus-1 -lpthread -lrt   -o ../xpi/platform/Linux_x86_64-gcc3/firesheep-backend src/main.cpp src/http_sniffer.cpp src/http_packet.cpp deps/http-parser/http_parser.c   src/linux_platform.cpp
/tmp/ccF4qH9k.o: In function `HttpSniffer::start()':
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:48: undefined reference to`pcap_open_live'
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:53: undefined reference to `pcap_datalink'
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:55: undefined reference to`pcap_datalink'
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:63: undefined reference to `pcap_compile'
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:67: undefined reference to`pcap_setfilter'
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:71: undefined reference to `pcap_loop'
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:74: undefined reference to`pcap_freecode'
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:75: undefined reference to `pcap_close'
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:64: undefined reference to`pcap_geterr'
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:68: undefined reference to `pcap_geterr'
/home/yuv/src/firesheep/backend/src/http_sniffer.cpp:59: undefined reference to`pcap_lookupnet'
/tmp/ccROxpoW.o: In function `device_get_property_string(LibHalContext_s*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, DBusError*)':
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:44: undefined reference to`libhal_device_get_property_string'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:45: undefined reference to `dbus_error_is_set'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:47: undefined reference to`dbus_error_free'
/tmp/ccROxpoW.o: In function `LinuxPlatform::interfaces()':
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:63: undefined reference to`libhal_ctx_new'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:68: undefined reference to `dbus_error_init'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:69: undefined reference to`dbus_bus_get'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:69: undefined reference to `libhal_ctx_set_dbus_connection'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:71: undefined reference to`dbus_error_is_set'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:71: undefined reference to `dbus_error_free'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:76: undefined reference to`libhal_ctx_init'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:77: undefined reference to `dbus_error_is_set'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:79: undefined reference to`dbus_error_free'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:87: undefined reference to `libhal_find_device_by_capability'
/home/yuv/src/firesheep/backend/src/linux_platform.cpp:131: undefined reference to`libhal_free_string_array'
collect2: ld returned 1 exit status
make[1]: **\* [../xpi/platform/Linux_x86_64-gcc3/firesheep-backend] Error 1
make[1]: Leaving directory `/home/yuv/src/firesheep/backend'
make: **\* [all-recursive] Error 1

What am I doing wrong?

**Comment by 4machiavelli4** [comment]
i have the same problem pleaz help us !!!

**Comment by codebutler** [comment]
The next release of Firesheep will officially support Linux.

**Comment by yuv** [comment]
Thank you!  Builds complete without complaints, but the xpi can't be installed in Firefox 5.

A change in install.rdf makes it installable, but then I get the following error when launching the preferences from the Add-ons Manager:

TypeError:Cc['@codebutler.com/mozpopen/process;1'] is undefined

and there is no interface listed.

Let me know if I can be of any help.

**Comment by agnxy** [comment]
Hello. I also encounter the same problem with yuv. I'm using Firefox 7 undex Ubuntu 11.04. Any advice? Thanks in advance.

**Comment by oliverkrystal** [comment]
@yuv, @Agnxy you will need to use the proper version of firesheep, with the proper version of firefox for this to work.  Changing the install.rdf won't help
